version: "3.7"
services:
  rails:
    platform: linux/x86_64
    build:
      context: .
    env_file:
      - rails.env
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: marvel_crud_api_production
      DB_PORT: 5432
      DB_HOST: db
      RAILS_MAX_THREADS: 5
      PORT: 3000
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - "db"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
